# Copyright 2026 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: deploy generated files

on:
  push:
    branches:
      - devel
      - master
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: deploy-generated-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
